/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "./stencil-public-runtime";
export namespace Components {
    interface Gw2Coin {
        "value": number;
    }
    interface Gw2Item {
        "currency": boolean;
        "itemId": number;
        "size": string;
    }
    interface Gw2Price {
        "buy": boolean;
        "itemId": number;
        "tax": number;
        "tptax": number;
    }
}
declare global {
    interface HTMLGw2CoinElement extends Components.Gw2Coin, HTMLStencilElement {
    }
    var HTMLGw2CoinElement: {
        prototype: HTMLGw2CoinElement;
        new (): HTMLGw2CoinElement;
    };
    interface HTMLGw2ItemElement extends Components.Gw2Item, HTMLStencilElement {
    }
    var HTMLGw2ItemElement: {
        prototype: HTMLGw2ItemElement;
        new (): HTMLGw2ItemElement;
    };
    interface HTMLGw2PriceElement extends Components.Gw2Price, HTMLStencilElement {
    }
    var HTMLGw2PriceElement: {
        prototype: HTMLGw2PriceElement;
        new (): HTMLGw2PriceElement;
    };
    interface HTMLElementTagNameMap {
        "gw2-coin": HTMLGw2CoinElement;
        "gw2-item": HTMLGw2ItemElement;
        "gw2-price": HTMLGw2PriceElement;
    }
}
declare namespace LocalJSX {
    interface Gw2Coin {
        "value"?: number;
    }
    interface Gw2Item {
        "currency"?: boolean;
        "itemId"?: number;
        "size"?: string;
    }
    interface Gw2Price {
        "buy"?: boolean;
        "itemId"?: number;
        "tax"?: number;
        "tptax"?: number;
    }
    interface IntrinsicElements {
        "gw2-coin": Gw2Coin;
        "gw2-item": Gw2Item;
        "gw2-price": Gw2Price;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "gw2-coin": LocalJSX.Gw2Coin & JSXBase.HTMLAttributes<HTMLGw2CoinElement>;
            "gw2-item": LocalJSX.Gw2Item & JSXBase.HTMLAttributes<HTMLGw2ItemElement>;
            "gw2-price": LocalJSX.Gw2Price & JSXBase.HTMLAttributes<HTMLGw2PriceElement>;
        }
    }
}
